repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      #- id: end-of-file-fixer
      #- id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-toml
  - repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
      - id: yapf
        additional_dependencies:
          - pyproject.toml
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies:
          - pyproject.toml
